#' Plots total number of Nino Registrations from EU, outside the EU and the total.
#' Assumes data is of type list by default and data frame is the first element of the list.
#' @param data data to plot: generated by year_to_date_sum()
#' @param date_filter column to extract
#' @param labels list of columns we want to extract
#' @return filtered data for plotting
#' @examples
#' \dontrun{extract_year_end_data(data, date_filter, labels)}


extract_year_end_date <- function(data, year_to_date, year_end_filter, labels){

  year_end_data <- dplyr::filter(data[[1]], grepl(year_to_date, unlist(data[[1]][2])))
  N = dim(year_end_data[1])[1]

  names.use <- names(year_end_data)[(names(year_end_data) %in% labels)]

  new_data<- year_end_data[, names.use]
  new_data <- cbind.data.frame(year_end_data[year_end_filter], new_data)
  colnames(new_data) <- c("quarter_dates", "EU15", "EU8", "EU2")

  new_data <- reshape2::melt(new_data, id.vars = year_end_filter, measure.vars = c("EU15", "EU8", "EU2"))
  new_data <- new_data[order(new_data[year_end_filter]), ]


  return(new_data)
}


#dd <- extract_year_end_date(data, "Dec", "quarter_dates", labels = c("European_Union_EU15",
#                                              "European_Union_EU2", "European_Union_EU8"))

